# Job Market Analysis

In [2]:
import pandas as pd

df = pd.read_csv(r"D:\OMKAR\Python\Job Career Analysis\indian_tech_career_intelligence_2026.csv")

df

,job_title,job_category,company_name,company_size,industry,company_type,location_city,location_state,location_country,work_mode,...,application_deadline,source_platform,applicant_count,job_benefits,technical_domain,interview_difficulty,probation_period,shift_type,is_active,career_growth_index
0,Machine Learning Engineer,AI / ML Engineering,TCS,"10,000+ employees",Information Technology,Top MNC,Delhi NCR,Delhi,India,On-site,...,16-03-2026,LinkedIn,193,"Stock Options (ESOPs), Free Meals, Remote Firs...",Core Applied Machine Learning,Medium,3 Months,Flexible Shift,False,85%
1,Full Stack Developer,Web Development,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Gurgaon,Haryana,India,Remote,...,1/3/2026,AmbitionBox,465,"Paid Time Off, Medical Cover, Annual Bonus",Frontend & Backend Engineering,Easy,3 Months,Flexible Shift,True,65%
2,Web Development Intern,Web Development,Cognizant,"10,000+ employees",Information Technology,Top MNC,Pune,Maharashtra,India,Remote,...,7/2/2026,Glassdoor,77,"Paid Time Off, Medical Cover, Annual Bonus",Frontend & Backend Engineering,Medium,6 Months,Flexible Shift,True,70%
3,DevOps Intern,DevOps Core,Infosys,"10,000+ employees",Information Technology,Top MNC,Gurgaon,Haryana,India,Remote,...,14-06-2026,AmbitionBox,387,"Health Insurance, Flexible Hours, Work from Ho...",Cloud & Infrastructure Systems,Medium,3 Months,Day Shift,True,84%
4,Cybersecurity Analyst,Cybersecurity,Swiggy,"1,000-5,000 employees",Information Technology,Tech Startup,Bangalore,Karnataka,India,On-site,...,22-06-2026,AmbitionBox,27,"Health Insurance, Flexible Hours, Work from Ho...",Network & Information Security,Hard,NaN,Day Shift,True,82%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,Data Scientist,Data Science,TCS,"10,000+ employees",Information Technology,Top MNC,Delhi NCR,Delhi,India,Hybrid,...,16-03-2026,LinkedIn,456,"Comprehensive Health Policy, Retirement Benefi...",Analytics & Business Intelligence,Easy,NaN,Day Shift,True,80%
99996,Azure Cloud Engineer,Cloud Architecture,Cred,100-500 employees,Information Technology,Tech Startup,Pune,Maharashtra,India,Remote,...,25-04-2026,Indeed,346,"Comprehensive Health Policy, Retirement Benefi...",Enterprise Cloud Systems,Medium,3 Months,Day Shift,True,69%
99997,Backend Developer,Web Development,Cred,100-500 employees,Information Technology,Tech Startup,Bangalore,Karnataka,India,On-site,...,22-06-2026,LinkedIn,98,"Health Insurance, Flexible Hours, Work from Ho...",Frontend & Backend Engineering,Easy,3 Months,Day Shift,False,70%
99998,Platform Engineer,DevOps Core,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Noida,Uttar Pradesh,India,Remote,...,28-03-2026,Naukri.com,236,"Comprehensive Health Policy, Retirement Benefi...",Cloud & Infrastructure Systems,Medium,NaN,Day Shift,False,68%
99999,AWS Solutions Architect,Cloud Architecture,Tech Mahindra,"10,000+ employees",Information Technology,Top MNC,Chennai,Tamil Nadu,India,Remote,...,10/2/2026,AmbitionBox,88,"Comprehensive Health Policy, Retirement Benefi...",Enterprise Cloud Systems,Medium,3 Months,Day Shift,False,95%

In [3]:
pd.set_option('display.max.rows', 1000)

In [4]:
df

,job_title,job_category,company_name,company_size,industry,company_type,location_city,location_state,location_country,work_mode,...,application_deadline,source_platform,applicant_count,job_benefits,technical_domain,interview_difficulty,probation_period,shift_type,is_active,career_growth_index
0,Machine Learning Engineer,AI / ML Engineering,TCS,"10,000+ employees",Information Technology,Top MNC,Delhi NCR,Delhi,India,On-site,...,16-03-2026,LinkedIn,193,"Stock Options (ESOPs), Free Meals, Remote Firs...",Core Applied Machine Learning,Medium,3 Months,Flexible Shift,False,85%
1,Full Stack Developer,Web Development,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Gurgaon,Haryana,India,Remote,...,1/3/2026,AmbitionBox,465,"Paid Time Off, Medical Cover, Annual Bonus",Frontend & Backend Engineering,Easy,3 Months,Flexible Shift,True,65%
2,Web Development Intern,Web Development,Cognizant,"10,000+ employees",Information Technology,Top MNC,Pune,Maharashtra,India,Remote,...,7/2/2026,Glassdoor,77,"Paid Time Off, Medical Cover, Annual Bonus",Frontend & Backend Engineering,Medium,6 Months,Flexible Shift,True,70%
3,DevOps Intern,DevOps Core,Infosys,"10,000+ employees",Information Technology,Top MNC,Gurgaon,Haryana,India,Remote,...,14-06-2026,AmbitionBox,387,"Health Insurance, Flexible Hours, Work from Ho...",Cloud & Infrastructure Systems,Medium,3 Months,Day Shift,True,84%
4,Cybersecurity Analyst,Cybersecurity,Swiggy,"1,000-5,000 employees",Information Technology,Tech Startup,Bangalore,Karnataka,India,On-site,...,22-06-2026,AmbitionBox,27,"Health Insurance, Flexible Hours, Work from Ho...",Network & Information Security,Hard,NaN,Day Shift,True,82%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,Data Scientist,Data Science,TCS,"10,000+ employees",Information Technology,Top MNC,Delhi NCR,Delhi,India,Hybrid,...,16-03-2026,LinkedIn,456,"Comprehensive Health Policy, Retirement Benefi...",Analytics & Business Intelligence,Easy,NaN,Day Shift,True,80%
99996,Azure Cloud Engineer,Cloud Architecture,Cred,100-500 employees,Information Technology,Tech Startup,Pune,Maharashtra,India,Remote,...,25-04-2026,Indeed,346,"Comprehensive Health Policy, Retirement Benefi...",Enterprise Cloud Systems,Medium,3 Months,Day Shift,True,69%
99997,Backend Developer,Web Development,Cred,100-500 employees,Information Technology,Tech Startup,Bangalore,Karnataka,India,On-site,...,22-06-2026,LinkedIn,98,"Health Insurance, Flexible Hours, Work from Ho...",Frontend & Backend Engineering,Easy,3 Months,Day Shift,False,70%
99998,Platform Engineer,DevOps Core,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Noida,Uttar Pradesh,India,Remote,...,28-03-2026,Naukri.com,236,"Comprehensive Health Policy, Retirement Benefi...",Cloud & Infrastructure Systems,Medium,NaN,Day Shift,False,68%
99999,AWS Solutions Architect,Cloud Architecture,Tech Mahindra,"10,000+ employees",Information Technology,Top MNC,Chennai,Tamil Nadu,India,Remote,...,10/2/2026,AmbitionBox,88,"Comprehensive Health Policy, Retirement Benefi...",Enterprise Cloud Systems,Medium,3 Months,Day Shift,False,95%

In [5]:
import numpy as np

df_clean = df.copy()

# Normalize column names
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
df

,job_title,job_category,company_name,company_size,industry,company_type,location_city,location_state,location_country,work_mode,...,application_deadline,source_platform,applicant_count,job_benefits,technical_domain,interview_difficulty,probation_period,shift_type,is_active,career_growth_index
0,Machine Learning Engineer,AI / ML Engineering,TCS,"10,000+ employees",Information Technology,Top MNC,Delhi NCR,Delhi,India,On-site,...,16-03-2026,LinkedIn,193,"Stock Options (ESOPs), Free Meals, Remote Firs...",Core Applied Machine Learning,Medium,3 Months,Flexible Shift,False,85%
1,Full Stack Developer,Web Development,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Gurgaon,Haryana,India,Remote,...,1/3/2026,AmbitionBox,465,"Paid Time Off, Medical Cover, Annual Bonus",Frontend & Backend Engineering,Easy,3 Months,Flexible Shift,True,65%
2,Web Development Intern,Web Development,Cognizant,"10,000+ employees",Information Technology,Top MNC,Pune,Maharashtra,India,Remote,...,7/2/2026,Glassdoor,77,"Paid Time Off, Medical Cover, Annual Bonus",Frontend & Backend Engineering,Medium,6 Months,Flexible Shift,True,70%
3,DevOps Intern,DevOps Core,Infosys,"10,000+ employees",Information Technology,Top MNC,Gurgaon,Haryana,India,Remote,...,14-06-2026,AmbitionBox,387,"Health Insurance, Flexible Hours, Work from Ho...",Cloud & Infrastructure Systems,Medium,3 Months,Day Shift,True,84%
4,Cybersecurity Analyst,Cybersecurity,Swiggy,"1,000-5,000 employees",Information Technology,Tech Startup,Bangalore,Karnataka,India,On-site,...,22-06-2026,AmbitionBox,27,"Health Insurance, Flexible Hours, Work from Ho...",Network & Information Security,Hard,NaN,Day Shift,True,82%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,Data Scientist,Data Science,TCS,"10,000+ employees",Information Technology,Top MNC,Delhi NCR,Delhi,India,Hybrid,...,16-03-2026,LinkedIn,456,"Comprehensive Health Policy, Retirement Benefi...",Analytics & Business Intelligence,Easy,NaN,Day Shift,True,80%
99996,Azure Cloud Engineer,Cloud Architecture,Cred,100-500 employees,Information Technology,Tech Startup,Pune,Maharashtra,India,Remote,...,25-04-2026,Indeed,346,"Comprehensive Health Policy, Retirement Benefi...",Enterprise Cloud Systems,Medium,3 Months,Day Shift,True,69%
99997,Backend Developer,Web Development,Cred,100-500 employees,Information Technology,Tech Startup,Bangalore,Karnataka,India,On-site,...,22-06-2026,LinkedIn,98,"Health Insurance, Flexible Hours, Work from Ho...",Frontend & Backend Engineering,Easy,3 Months,Day Shift,False,70%
99998,Platform Engineer,DevOps Core,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Noida,Uttar Pradesh,India,Remote,...,28-03-2026,Naukri.com,236,"Comprehensive Health Policy, Retirement Benefi...",Cloud & Infrastructure Systems,Medium,NaN,Day Shift,False,68%
99999,AWS Solutions Architect,Cloud Architecture,Tech Mahindra,"10,000+ employees",Information Technology,Top MNC,Chennai,Tamil Nadu,India,Remote,...,10/2/2026,AmbitionBox,88,"Comprehensive Health Policy, Retirement Benefi...",Enterprise Cloud Systems,Medium,3 Months,Day Shift,False,95%

In [6]:
df_clean = df_clean.drop_duplicates().copy()

# Convert dates
for col in ["posted_date", "application_deadline"]:
    df_clean[col] = pd.to_datetime(
        df_clean[col], errors="coerce"
    )

# Convert numeric columns
numeric_cols = [
    "salary_minimum",
    "salary_maximum",
     "stipend_amount",
    "skill_count",
    "experience_required",
    "applicant_count",
    "career_growth_index",
]

for col in numeric_cols:
    df_clean[col] = pd.to_numeric(
        df_clean[col], errors="coerce"
    )

# Inspect cleaning results
print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)
print("Missing values:")
print(df_clean.isna().sum().sort_values(ascending=False).head(15))

C:\Users\pawar\AppData\Local\Temp\ipykernel_8232\3557486623.py:6: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_clean[col] = pd.to_datetime(
C:\Users\pawar\AppData\Local\Temp\ipykernel_8232\3557486623.py:6: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_clean[col] = pd.to_datetime(

Original shape: (100000, 33)
Cleaned shape: (100000, 33)
Missing values:
experience_required     100000
career_growth_index     100000
posted_date              39943
application_deadline     39867
probation_period         33499
job_title                    0
job_category                 0
company_size                 0
company_name                 0
location_country             0
work_mode                    0
salary_maximum               0
salary_minimum               0
company_type                 0
location_city                0
dtype: int64

In [7]:
# Top 10 job categories
category_demand = (
    df_clean["job_category"]
    .value_counts()
    .head(10)
)

display(category_demand)

# Top cities
city_demand = (
    df_clean["location_city"]
    .value_counts()
    .head(10)
)

display(city_demand)

# Work mode distribution
display(df_clean["work_mode"].value_counts())

# Experience level distribution
display(df_clean["experience_level"].value_counts())

job_category
Web Development        16872
AI / ML Engineering    16787
Cloud Architecture     16782
DevOps Core            16697
Cybersecurity          16437
Data Science           16425
Name: count, dtype: int64

location_city
Chennai      12636
Noida        12622
Gurgaon      12521
Delhi NCR    12515
Pune         12452
Mumbai       12443
Hyderabad    12439
Bangalore    12372
Name: count, dtype: int64

work_mode
Remote     40018
Hybrid     39654
On-site    20328
Name: count, dtype: int64

experience_level
Mid-Senior Level          59871
Freshers / Entry Level    40129
Name: count, dtype: int64

In [8]:
salary_df = df_clean[
    (df_clean["salary_minimum"] > 0) &
    (df_clean["salary_maximum"] >= df_clean["salary_minimum"])
].copy()

salary_by_role = (
    salary_df.groupby("job_category")
    .agg(
        job_count=("job_title", "count"),
        median_min_salary=("salary_minimum", "median"),
        median_max_salary=("salary_maximum", "median")
    )
    .sort_values("median_max_salary", ascending=False)
)

display(salary_by_role.head(15))

                     job_count  median_min_salary  median_max_salary
job_category
DevOps Core              16697           447465.0          1253483.0
Cloud Architecture       16782           449582.5          1252370.5
Cybersecurity            16437           449626.0          1250689.0
AI / ML Engineering      16787           450797.0          1250322.0
Web Development          16872           450486.5          1249320.0
Data Science             16425           450769.0          1248438.0

In [9]:
skill_series = (
    df_clean["skills_extracted"]
    .dropna()
    .astype(str)
    .str.split(",")
    .explode()
    .str.strip()
    .str.lower()
)

skill_counts = (
    skill_series[skill_series.ne("")]
    .value_counts()
    .head(20)
)

display(skill_counts)

skills_extracted
python            33212
linux             33134
html              16872
css               16872
javascript        16872
react             16872
node.js           16872
express           16872
mongodb           16872
tailwind css      16872
pytorch           16787
tensorflow        16787
scikit-learn      16787
openai api        16787
huggingface       16787
aws               16782
azure             16782
cloudformation    16782
iam               16782
ec2               16782
Name: count, dtype: int64

In [10]:
sample_df = df.sample(
    n=min(500, len(df)),
    random_state=42
)
sample_df

,job_title,job_category,company_name,company_size,industry,company_type,location_city,location_state,location_country,work_mode,...,application_deadline,source_platform,applicant_count,job_benefits,technical_domain,interview_difficulty,probation_period,shift_type,is_active,career_growth_index
75721,Frontend Engineer,Web Development,HCLTech,"10,000+ employees",Information Technology,Top MNC,Gurgaon,Haryana,India,On-site,...,26-06-2026,AmbitionBox,37,"Health Insurance, Flexible Hours, Work from Ho...",Frontend & Backend Engineering,Medium,3 Months,Flexible Shift,True,79%
80184,Full Stack Developer,Web Development,Cognizant,"10,000+ employees",Information Technology,Top MNC,Delhi NCR,Delhi,India,Hybrid,...,8/5/2026,LinkedIn,431,"Performance Incentives, Skill Upskilling Allow...",Frontend & Backend Engineering,Hard,NaN,Day Shift,True,76%
19864,Site Reliability Engineer,DevOps Core,HCLTech,"10,000+ employees",Information Technology,Top MNC,Bangalore,Karnataka,India,On-site,...,9/4/2026,Naukri.com,454,"Health Insurance, Flexible Hours, Work from Ho...",Cloud & Infrastructure Systems,Medium,NaN,Day Shift,True,87%
76699,Cloud DevOps Engineer,DevOps Core,Wipro,"10,000+ employees",Information Technology,Top MNC,Hyderabad,Telangana,India,Remote,...,5/2/2026,AmbitionBox,250,"Health Insurance, Flexible Hours, Work from Ho...",Cloud & Infrastructure Systems,Medium,NaN,Night Shift,True,93%
92991,Data Analytics Intern,Data Science,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Hyderabad,Telangana,India,On-site,...,28-02-2026,AmbitionBox,185,"Comprehensive Health Policy, Retirement Benefi...",Analytics & Business Intelligence,Medium,6 Months,Day Shift,True,80%
76434,Data Scientist,Data Science,Cred,100-500 employees,Information Technology,Tech Startup,Pune,Maharashtra,India,Hybrid,...,21-06-2026,AmbitionBox,260,"Health Insurance, Flexible Hours, Work from Ho...",Analytics & Business Intelligence,Medium,3 Months,Flexible Shift,True,71%
84004,Computer Vision Engineer,AI / ML Engineering,TCS,"10,000+ employees",Information Technology,Top MNC,Mumbai,Maharashtra,India,Hybrid,...,27-06-2026,LinkedIn,460,"Health Insurance, Flexible Hours, Work from Ho...",Core Applied Machine Learning,Hard,3 Months,Day Shift,True,92%
80917,Machine Learning Engineer,AI / ML Engineering,Swiggy,"1,000-5,000 employees",Information Technology,Tech Startup,Delhi NCR,Delhi,India,On-site,...,2/5/2026,Naukri.com,267,"Comprehensive Health Policy, Retirement Benefi...",Core Applied Machine Learning,Easy,6 Months,Day Shift,True,66%
60767,AI Research Intern,AI / ML Engineering,Cred,100-500 employees,Information Technology,Tech Startup,Noida,Uttar Pradesh,India,On-site,...,19-04-2026,Naukri.com,242,"Stock Options (ESOPs), Free Meals, Remote Firs...",Core Applied Machine Learning,Easy,6 Months,Day Shift,True,74%
50074,DevOps Intern,DevOps Core,Razorpay,"500-1,000 employees",Information Technology,Fintech Unicorn,Hyderabad,Telangana,India,Remote,...,23-02-2026,Indeed,31,"Performance Incentives, Skill Upskilling Allow...",Cloud & Infrastructure Systems,Medium,6 Months,Day Shift,False,80%
27701,Business Analyst,Data Science,Infosys,"10,000+ employees",Information Technology,Top MNC,Pune,Maharashtra,India,On-site,...,10/3/2026,Glassdoor,84,"Paid Time Off, Medical Cover, Annual Bonus",Analytics & Business Intelligence,Medium,3 Months,Day Shift,True,69%
42141,Cybersecurity Analyst,Cybersecurity,Infosys,"10,000+ employees",Information Technology,Top MNC,Mumbai,Maharashtra,India,Hybrid,...,19-04-2026,Naukri.com,150,"Comprehensive Health Policy, Retirement Benefi...",Network & Information Security,Medium,3 Months,Day Shift,False,76%
45080,Data Scientist,Data Science,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Hyderabad,Telangana,India,Remote,...,10/5/2026,Naukri.com,374,"Comprehensive Health Policy, Retirement Benefi...",Analytics & Business Intelligence,Hard,3 Months,Day Shift,False,70%
16638,DevOps Intern,DevOps Core,Wipro,"10,000+ employees",Information Technology,Top MNC,Delhi NCR,Delhi,India,Remote,...,24-06-2026,Indeed,65,"Performance Incentives, Skill Upskilling Allow...",Cloud & Infrastructure Systems,Easy,6 Months,Day Shift,True,90%
20424,Azure Cloud Engineer,Cloud Architecture,Swiggy,"1,000-5,000 employees",Information Technology,Tech Startup,Delhi NCR,Delhi,India,Hybrid,...,1/4/2026,AmbitionBox,323,"Paid Time Off, Medical Cover, Annual Bonus",Enterprise Cloud Systems,Medium,NaN,Day Shift,True,69%
88702,Machine Learning Engineer,AI / ML Engineering,Cred,100-500 employees,Information Technology,Tech Startup,Chennai,Tamil Nadu,India,Remote,...,8/2/2026,Glassdoor,177,"Comprehensive Health Policy, Retirement Benefi...",Core Applied Machine Learning,Medium,6 Months,Flexible Shift,True,65%
149,Data Scientist,Data Science,Cognizant,"10,000+ employees",Information Technology,Top MNC,Mumbai,Maharashtra,India,On-site,...,12/6/2026,Naukri.com,200,"Stock Options (ESOPs), Free Meals, Remote Firs...",Analytics & Business Intelligence,Hard,NaN,Night Shift,True,96%
1761,Data Engineer,Data Science,Infosys,"10,000+ employees",Information Technology,Top MNC,Bangalore,Karnataka,India,Remote,...,26-05-2026,Indeed,165,"Paid Time Off, Medical Cover, Annual Bonus",Analytics & Business Intelligence,Easy,3 Months,Night Shift,True,70%
63120,Data Scientist,Data Science,Swiggy,"1,000-5,000 employees",Information Technology,Tech Startup,Bangalore,Karnataka,India,On-site,...,13-02-2026,AmbitionBox,357,"Health Insurance, Flexible Hours, Work from Ho...",Analytics & Business Intelligence,Easy,6 Months,Day Shift,True,84%
69161,Platform Engineer,DevOps Core,HCLTech,"10,000+ employees",Information Technology,Top MNC,Gurgaon,Haryana,India,Hybrid,...,16-06-2026,AmbitionBox,341,"Health Insurance, Flexible Hours, Work from Ho...",Cloud & Infrastructure Systems,Medium,NaN,Day Shift,True,69%
64883,Azure Cloud Engineer,Cloud Architecture,Cred,100-500 employees,Information Technology,Tech Startup,Bangalore,Karnataka,India,Hybrid,...,10/6/2026,Indeed,405,"Paid Time Off, Medical Cover, Annual Bonus",Enterprise Cloud Systems,Medium,6 Months,Day Shift,True,90%
2495,AI Research Intern,AI / ML Engineering,HCLTech,"10,000+ employees",Information Technology,Top MNC,Mumbai,Maharashtra,India,Hybrid,...,16-06-2026,LinkedIn,346,"Health Insurance, Flexible Hours, Work from Ho...",Core Applied Machine Learning,Medium,3 Months,Day Shift,True,94%
80296,Web Development Intern,Web Development,Tech Mahindra,"10,000+ employees",Information Technology,Top MNC,Mumbai,Maharashtra,India,Hybrid,...,4/3/2026,LinkedIn,163,"Health Insurance, Flexible Hours, Work from Ho...",Frontend & Backend Engineering,Hard,6 Months,Day Shift,True,71%
19447,Data Analytics Intern,Data Science,Wipro,"10,000+ employees",Information Technology,Top MNC,Delhi NCR,Delhi,India,Remote,...,10/3/2026,LinkedIn,26,"Paid Time Off, Medical Cover, Annual Bonus",Analytics & Business Intelligence,Medium,6 Months,Day Shift,True,75%
41331,React Developer,Web Development,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Noida,Uttar Pradesh,India,Hybrid,...,28-02-2026,Indeed,225,"Paid Time Off, Medical Cover, Annual Bonus",Frontend & Backend Engineering,Medium,NaN,Flexible Shift,True,68%
14888,Computer Vision Engineer,AI / ML Engineering,Razorpay,"500-1,000 employees",Information Technology,Fintech Unicorn,Noida,Uttar Pradesh,India,On-site,...,5/2/2026,LinkedIn,58,"Stock Options (ESOPs), Free Meals, Remote Firs...",Core Applied Machine Learning,Medium,NaN,Day Shift,False,97%
88636,Azure Cloud Engineer,Cloud Architecture,Cognizant,"10,000+ employees",Information Technology,Top MNC,Mumbai,Maharashtra,India,On-site,...,21-02-2026,Glassdoor,36,"Paid Time Off, Medical Cover, Annual Bonus",Enterprise Cloud Systems,Medium,NaN,Night Shift,True,71%
94892,Data Analytics Intern,Data Science,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Gurgaon,Haryana,India,Hybrid,...,23-06-2026,AmbitionBox,172,"Comprehensive Health Policy, Retirement Benefi...",Analytics & Business Intelligence,Medium,6 Months,Day Shift,False,81%
92731,Cloud Infrastructure Intern,Cloud Architecture,Razorpay,"500-1,000 employees",Information Technology,Fintech Unicorn,Mumbai,Maharashtra,India,On-site,...,25-05-2026,Indeed,461,"Paid Time Off, Medical Cover, Annual Bonus",Enterprise Cloud Systems,Medium,3 Months,Day Shift,True,84%
29130,Platform Engineer,DevOps Core,Razorpay,"500-1,000 employees",Information Technology,Fintech Unicorn,Delhi NCR,Delhi,India,Hybrid,...,24-02-2026,Indeed,311,"Paid Time Off, Medical Cover, Annual Bonus",Cloud & Infrastructure Systems,Hard,NaN,Day Shift,True,67%
79022,Cybersecurity Analyst,Cybersecurity,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Noida,Uttar Pradesh,India,Hybrid,...,7/3/2026,AmbitionBox,140,"Stock Options (ESOPs), Free Meals, Remote Firs...",Network & Information Security,Medium,NaN,Flexible Shift,True,72%
84936,AWS Solutions Architect,Cloud Architecture,HCLTech,"10,000+ employees",Information Technology,Top MNC,Bangalore,Karnataka,India,Hybrid,...,18-05-2026,LinkedIn,440,"Stock Options (ESOPs), Free Meals, Remote Firs...",Enterprise Cloud Systems,Hard,3 Months,Day Shift,True,79%
16821,Business Analyst,Data Science,Swiggy,"1,000-5,000 employees",Information Technology,Tech Startup,Hyderabad,Telangana,India,Hybrid,...,18-04-2026,Indeed,93,"Performance Incentives, Skill Upskilling Allow...",Analytics & Business Intelligence,Medium,6 Months,Day Shift,True,97%
36733,Penetration Tester,Cybersecurity,Zomato,"1,000-5,000 employees",Information Technology,Tech Startup,Pune,Maharashtra,India,Hybrid,...,31-03-2026,Naukri.com,413,"Paid Time Off, Medical Cover, Annual Bonus",Network & Information Security,Hard,NaN,Day Shift,True,89%
15602,Machine Learning Engineer,AI / ML Engineering,Cred,100-500 employees,Information Technology,Tech Startup,Noida,Uttar Pradesh,India,Hybrid,...,16-05-2026,LinkedIn,73,"Comprehensive Health Policy, Retirement Benefi...",Core Applied Machine Learning,Medium,3 Months,Day Shift,True,66%
28533,Computer Vision Engineer,AI / ML Engineering,Paytm,"1,000-5,000 employees",Information Technology,Fintech Unicorn,Chennai,Tamil Nadu,India,Remote,...,3/6/2026,Glassdoor,232,"Stock Options (ESOPs), Free Meals, Remote Firs...",Core Applied Machine Learning,Medium,6 Months,Day Shift,True,65%
69769,Cloud DevOps Engineer,DevOps Core,Wipro,"10,000+ employees",Information Technology,Top MNC,Delhi NCR,Delhi,India,Hybrid,...,14-06-2026,LinkedIn,202,"Paid Time Off, Medical Cover, Annual Bonus",Cloud & Infrastructure Systems,Medium,3 Months,Day Shift,False,78%
11405,Cybersecurity Analyst,Cybersecurity,Cognizant,"10,000+ employees",Information Technology,Top MNC,Bangalore,Karnataka,India,On-site,...,24-03-2026,Glassdoor,324,"Stock Options (ESOPs), Free Meals, Remote Firs...",Network & Information Security,Medium,6 Months,Day Shift,True,66%
96852,AWS Solutions Architect,Cloud Architecture,Infosys,"10,000+ employees",Information Technology,Top MNC,Gurgaon,Haryana,India,Hybrid,...,29-05-2026,AmbitionBox,89,"Stock Options (ESOPs), Free Meals, Remote Firs...",Enterprise Cloud Systems,Medium,3 Months,Day Shift,True,97%
16130,Data Analytics Intern,Data Science,Wipro,"10,000+ employees",Information Technology,Top MNC,Mumbai,Maharashtra,India,Remote,...,5/3/2026,Indeed,201,"Stock Options (ESOPs), Free Meals, Remote Firs...",Analytics & Business Intelligence,Medium,NaN,Day Shift,True,96%
19792,Backend Developer,Web Development,Razorpay,"500-1,000 employees",Information Technology,Fintech Unicorn,Chennai,Tamil Nadu,India,Remote,...,10/4/2026,Indeed,475,"Stock Options (ESOPs), Free Meals, Remote Firs...",Frontend & Backend Engineering,Easy,6 Months,Night Shift,False,91%
89577,Frontend Engineer,Web Development,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Delhi NCR,Delhi,India,Remote,...,4/4/2026,Glassdoor,237,"Comprehensive Health Policy, Retirement Benefi...",Frontend & Backend Engineering,Medium,NaN,Day Shift,False,74%
40163,Azure Cloud Engineer,Cloud Architecture,TCS,"10,000+ employees",Information Technology,Top MNC,Noida,Uttar Pradesh,India,Hybrid,...,19-06-2026,AmbitionBox,224,"Health Insurance, Flexible Hours, Work from Ho...",Enterprise Cloud Systems,Hard,3 Months,Flexible Shift,True,98%
31776,Penetration Tester,Cybersecurity,Zomato,"1,000-5,000 employees",Information Technology,Tech Startup,Pune,Maharashtra,India,Remote,...,15-04-2026,Glassdoor,474,"Comprehensive Health Policy, Retirement Benefi...",Network & Information Security,Hard,NaN,Day Shift,False,88%
25330,Azure Cloud Engineer,Cloud Architecture,Cred,100-500 employees,Information Technology,Tech Startup,Gurgaon,Haryana,India,Hybrid,...,20-03-2026,LinkedIn,326,"Comprehensive Health Policy, Retirement Benefi...",Enterprise Cloud Systems,Medium,NaN,Day Shift,False,96%
79156,Cloud DevOps Engineer,DevOps Core,Cognizant,"10,000+ employees",Information Technology,Top MNC,Pune,Maharashtra,India,Hybrid,...,12/4/2026,Indeed,87,"Stock Options (ESOPs), Free Meals, Remote Firs...",Cloud & Infrastructure Systems,Medium,NaN,Day Shift,True,90%
51685,SOC Analyst,Cybersecurity,Swiggy,"1,000-5,000 employees",Information Technology,Tech Startup,Bangalore,Karnataka,India,Remote,...,27-04-2026,Indeed,55,"Health Insurance, Flexible Hours, Work from Ho...",Network & Information Security,Hard,6 Months,Day Shift,True,75%
75498,Data Scientist,Data Science,Cred,100-500 employees,Information Technology,Tech Startup,Mumbai,Maharashtra,India,Hybrid,...,28-02-2026,Glassdoor,87,"Comprehensive Health Policy, Retirement Benefi...",Analytics & Business Intelligence,Medium,3 Months,Flexible Shift,True,74%
4727,Penetration Tester,Cybersecurity,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Chennai,Tamil Nadu,India,On-site,...,11/5/2026,Indeed,304,"Stock Options (ESOPs), Free Meals, Remote Firs...",Network & Information Security,Easy,NaN,Day Shift,True,84%
85198,SOC Analyst,Cybersecurity,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Mumbai,Maharashtra,India,Remote,...,23-06-2026,LinkedIn,18,"Stock Options (ESOPs), Free Meals, Remote Firs...",Network & Information Security,Medium,3 Months,Day Shift,True,85%
35795,AI Research Intern,AI / ML Engineering,Cred,100-500 employees,Information Technology,Tech Startup,Delhi NCR,Delhi,India,Remote,...,9/2/2026,Naukri.com,149,"Paid Time Off, Medical Cover, Annual Bonus",Core Applied Machine Learning,Hard,3 Months,Day Shift,True,81%
12256,Frontend Engineer,Web Development,Wipro,"10,000+ employees",Information Technology,Top MNC,Hyderabad,Telangana,India,Remote,...,24-04-2026,AmbitionBox,86,"Performance Incentives, Skill Upskilling Allow...",Frontend & Backend Engineering,Easy,6 Months,Day Shift,True,79%
35718,Platform Engineer,DevOps Core,HCLTech,"10,000+ employees",Information Technology,Top MNC,Pune,Maharashtra,India,On-site,...,5/6/2026,AmbitionBox,248,"Performance Incentives, Skill Upskilling Allow...",Cloud & Infrastructure Systems,Medium,3 Months,Flexible Shift,True,90%
70551,Cybersecurity Analyst,Cybersecurity,Cognizant,"10,000+ employees",Information Technology,Top MNC,Gurgaon,Haryana,India,Remote,...,13-05-2026,Glassdoor,51,"Comprehensive Health Policy, Retirement Benefi...",Network & Information Security,Medium,NaN,Day Shift,True,65%
54374,Backend Developer,Web Development,Cred,100-500 employees,Information Technology,Tech Startup,Chennai,Tamil Nadu,India,Hybrid,...,15-05-2026,LinkedIn,435,"Performance Incentives, Skill Upskilling Allow...",Frontend & Backend Engineering,Medium,NaN,Flexible Shift,False,97%
39691,Frontend Engineer,Web Development,Razorpay,"500-1,000 employees",Information Technology,Fintech Unicorn,Chennai,Tamil Nadu,India,Hybrid,...,6/6/2026,LinkedIn,152,"Health Insurance, Flexible Hours, Work from Ho...",Frontend & Backend Engineering,Medium,3 Months,Flexible Shift,True,91%
93702,Cybersecurity Analyst,Cybersecurity,Infosys,"10,000+ employees",Information Technology,Top MNC,Bangalore,Karnataka,India,Remote,...,1/6/2026,Naukri.com,304,"Performance Incentives, Skill Upskilling Allow...",Network & Information Security,Hard,NaN,Day Shift,True,67%
73691,Business Analyst,Data Science,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Mumbai,Maharashtra,India,On-site,...,18-04-2026,LinkedIn,243,"Comprehensive Health Policy, Retirement Benefi...",Analytics & Business Intelligence,Medium,3 Months,Day Shift,True,98%
98070,Computer Vision Engineer,AI / ML Engineering,Cred,100-500 employees,Information Technology,Tech Startup,Hyderabad,Telangana,India,Remote,...,5/5/2026,Naukri.com,339,"Comprehensive Health Policy, Retirement Benefi...",Core Applied Machine Learning,Easy,6 Months,Night Shift,True,96%
575,DevOps Intern,DevOps Core,Wipro,"10,000+ employees",Information Technology,Top MNC,Mumbai,Maharashtra,India,Remote,...,18-04-2026,Indeed,309,"Comprehensive Health Policy, Retirement Benefi...",Cloud & Infrastructure Systems,Easy,NaN,Flexible Shift,True,92%
84610,Azure Cloud Engineer,Cloud Architecture,Tech Mahindra,"10,000+ employees",Information Technology,Top MNC,Hyderabad,Telangana,India,Remote,...,20-02-2026,LinkedIn,137,"Performance Incentives, Skill Upskilling Allow...",Enterprise Cloud Systems,Hard,6 Months,Night Shift,True,98%
61769,Backend Developer,Web Development,Razorpay,"500-1,000 employees",Information Technology,Fintech Unicorn,Hyderabad,Telangana,India,Hybrid,...,2/5/2026,AmbitionBox,406,"Health Insurance, Flexible Hours, Work from Ho...",Frontend & Backend Engineering,Medium,NaN,Day Shift,True,86%
32260,Cloud DevOps Engineer,DevOps Core,Infosys,"10,000+ employees",Information Technology,Top MNC,Hyderabad,Telangana,India,On-site,...,7/2/2026,Glassdoor,451,"Paid Time Off, Medical Cover, Annual Bonus",Cloud & Infrastructure Systems,Medium,NaN,Flexible Shift,True,69%
82199,AI Research Intern,AI / ML Engineering,Cred,100-500 employees,Information Technology,Tech Startup,Gurgaon,Haryana,India,Remote,...,9/6/2026,LinkedIn,243,"Stock Options (ESOPs), Free Meals, Remote Firs...",Core Applied Machine Learning,Hard,3 Months,Night Shift,True,90%
36290,Platform Engineer,DevOps Core,Infosys,"10,000+ employees",Information Technology,Top MNC,Delhi NCR,Delhi,India,On-site,...,27-06-2026,LinkedIn,437,"Paid Time Off, Medical Cover, Annual Bonus",Cloud & Infrastructure Systems,Medium,3 Months,Day Shift,True,65%
78449,AI Research Intern,AI / ML Engineering,Zomato,"1,000-5,000 employees",Information Technology,Tech Startup,Hyderabad,Telangana,India,Hybrid,...,28-02-2026,AmbitionBox,170,"Comprehensive Health Policy, Retirement Benefi...",Core Applied Machine Learning,Hard,6 Months,Night Shift,False,91%
60055,AWS Solutions Architect,Cloud Architecture,Infosys,"10,000+ employees",Information Technology,Top MNC,Bangalore,Karnataka,India,Remote,...,17-05-2026,AmbitionBox,67,"Performance Incentives, Skill Upskilling Allow...",Enterprise Cloud Systems,Medium,NaN,Flexible Shift,False,84%
45948,Machine Learning Engineer,AI / ML Engineering,Tech Mahindra,"10,000+ employees",Information Technology,Top MNC,Chennai,Tamil Nadu,India,Hybrid,...,25-03-2026,Glassdoor,380,"Comprehensive Health Policy, Retirement Benefi...",Core Applied Machine Learning,Medium,3 Months,Day Shift,True,81%
28177,Cloud Infrastructure Intern,Cloud Architecture,Swiggy,"1,000-5,000 employees",Information Technology,Tech Startup,Chennai,Tamil Nadu,India,On-site,...,21-06-2026,LinkedIn,299,"Paid Time Off, Medical Cover, Annual Bonus",Enterprise Cloud Systems,Easy,3 Months,Day Shift,True,88%
84463,Backend Developer,Web Development,Swiggy,"1,000-5,000 employees",Information Technology,Tech Startup,Delhi NCR,Delhi,India,Remote,...,18-05-2026,Naukri.com,61,"Performance Incentives, Skill Upskilling Allow...",Frontend & Backend Engineering,Medium,3 Months,Day Shift,True,85%

In [11]:
sample_df.to_csv(
    "job_market_sample_500.csv",
    index=False
)

In [16]:
df2 = pd.read_csv(r"D:\OMKAR\Python\Job Career Analysis\job_market_sample_500.csv")
numeric_cols = [
    "salary_minimum",
    "salary_maximum",
     "stipend_amount",
    "skill_count",
    "experience_required",
    "applicant_count",
    "career_growth_index",
]

In [13]:
for col in numeric_cols:
    df2[col] = pd.to_numeric(
        df2[col], errors="coerce"
    )

In [22]:
print("Original shape:", df2.shape)
print("Cleaned shape:", df2.shape)
print("Missing values:")
print(df2.isna().sum().sort_values(ascending=False).head(15))

Original shape: (500, 33)
Cleaned shape: (500, 33)
Missing values:
probation_period    178
job_title             0
job_category          0
company_size          0
company_name          0
company_type          0
location_city         0
location_state        0
industry              0
work_mode             0
salary_minimum        0
salary_maximum        0
salary_currency       0
stipend_amount        0
experience_level      0
dtype: int64

In [18]:
# Top 10 job categories
category_demand = (
    df2["job_category"]
    .value_counts()
    .head(10)
)

display(category_demand)

# Top cities
city_demand = (
    df2["location_city"]
    .value_counts()
    .head(10)
)

display(city_demand)

# Work mode distribution
display(df2["work_mode"].value_counts())

# Experience level distribution
display(df2["experience_level"].value_counts())

job_category
Data Science           90
AI / ML Engineering    89
DevOps Core            82
Web Development        81
Cloud Architecture     81
Cybersecurity          77
Name: count, dtype: int64

location_city
Bangalore    72
Mumbai       69
Chennai      68
Delhi NCR    65
Pune         61
Hyderabad    59
Gurgaon      54
Noida        52
Name: count, dtype: int64

work_mode
Hybrid     194
Remote     185
On-site    121
Name: count, dtype: int64

experience_level
Mid-Senior Level          296
Freshers / Entry Level    204
Name: count, dtype: int64

In [19]:
salary_df = df_clean[
    (df_clean["salary_minimum"] > 0) &
    (df_clean["salary_maximum"] >= df_clean["salary_minimum"])
].copy()

salary_by_role = (
    salary_df.groupby("job_category")
    .agg(
        job_count=("job_title", "count"),
        median_min_salary=("salary_minimum", "median"),
        median_max_salary=("salary_maximum", "median")
    )
    .sort_values("median_max_salary", ascending=False)
)

display(salary_by_role.head(15))

                     job_count  median_min_salary  median_max_salary
job_category
DevOps Core              16697           447465.0          1253483.0
Cloud Architecture       16782           449582.5          1252370.5
Cybersecurity            16437           449626.0          1250689.0
AI / ML Engineering      16787           450797.0          1250322.0
Web Development          16872           450486.5          1249320.0
Data Science             16425           450769.0          1248438.0

In [20]:
skill_series = (
    df_clean["skills_extracted"]
    .dropna()
    .astype(str)
    .str.split(",")
    .explode()
    .str.strip()
    .str.lower()
)

skill_counts = (
    skill_series[skill_series.ne("")]
    .value_counts()
    .head(20)
)

display(skill_counts)

skills_extracted
python            33212
linux             33134
html              16872
css               16872
javascript        16872
react             16872
node.js           16872
express           16872
mongodb           16872
tailwind css      16872
pytorch           16787
tensorflow        16787
scikit-learn      16787
openai api        16787
huggingface       16787
aws               16782
azure             16782
cloudformation    16782
iam               16782
ec2               16782
Name: count, dtype: int64